### ISSUE TITLE
Make ingress TLS secret configurable

### ISSUE THREAD

**Issue by rouke-broersma** [FlorisFeddema/homelab#620]
Including empty

**Comment by FlorisFeddema** [comment]
Does this work for you?

**Comment by rouke-broersma** [comment]
https://github.com/FlorisFeddema/homelab/commit/209e47aebb7fa63f433ed1dcc6cc5afd9e87e129

This change works for me but it looks like you later changed it to optional ingress with required tls secret. I guess I can turn off ingress from the chart and supply my own.
